name: Workflow Web Auto

on: 
 push:
  branches: [ 'develop' ]

jobs:
  
  testing:
    runs-on: ubuntu-latest
    container: crowdar/lippia:3.1.2.2
    env: 
      TAG: "@smoke"
      #LANG: "@EN"
      BROWSERTYPE: "chromeHeadless"
    
    steps:
    - uses: actions/checkout@v3
    - name: valores de las variables de entorno
      run: echo "TAG= "$TAG,
                "TESTTYPE= "$TESTTYPE,
                "BROWSERTYPE= "$BROWSERTYPE
    - name: Realizando Pruebas
      run: mvn clean test -P$BROWSERTYPE -Dcucumber.tags="--tags $TAG"
    - name: Subiendo informe
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r dir.zip *
